require('dotenv').config();
const express = require('express');
const cors = require('cors');
const connectDB = require('./config/db');
const app = express();
app.use(express.json());
app.use(cors({ origin: true, credentials: true }));
connectDB(process.env.MONGO_URI || 'mongodb://127.0.0.1:27017/moviereviewer');
app.use('/api/auth', require('./routes/auth'));
app.use('/api/movies', require('./routes/movies'));
app.use('/api/reviews', require('./routes/reviews'));
const PORT = process.env.PORT || 5000;
app.listen(PORT, () => console.log(`Server running on ${PORT}`));
